# Generated by Django 4.2.23 on 2025-09-02 02:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ownerId",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("isInternalAccount", models.BooleanField(default=False)),
                (
                    "accountId",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True
                    ),
                ),
                ("accountType", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "subAccountType",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "accountNumber",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "accountName",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "officialAccountName",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "availableBalance",
                    models.FloatField(blank=True, default=0, null=True),
                ),
                ("currentBalance", models.FloatField(blank=True, default=0, null=True)),
                ("createdDate", models.DateTimeField(blank=True, null=True)),
                ("updatedDate", models.DateTimeField(blank=True, null=True)),
                (
                    "transactionsUpdatedDate",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("balancedUpdatedDate", models.DateTimeField(blank=True, null=True)),
                ("icon", models.IntegerField(blank=True, null=True)),
                (
                    "isoCurrencyCode",
                    models.CharField(blank=True, max_length=16, null=True),
                ),
                (
                    "unofficialCurrencyCode",
                    models.CharField(blank=True, max_length=16, null=True),
                ),
                ("limit", models.FloatField(blank=True, null=True)),
                ("loans", models.FloatField(blank=True, null=True)),
                ("depts", models.FloatField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AccountBalances",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ownerId",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("income", models.FloatField(blank=True, default=0, null=True)),
                ("expanses", models.FloatField(blank=True, default=0, null=True)),
                ("balance", models.FloatField(blank=True, default=0, null=True)),
                ("balanceMonth", models.CharField(max_length=32)),
                ("balancedUpdatedDate", models.DateTimeField(blank=True, null=True)),
                (
                    "account",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="finance.account",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Bills",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ownerId",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("amount", models.FloatField(blank=True, null=True)),
                (
                    "repeat",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ONE_TIME_ONLY", "One time only"),
                            ("WEEKLY", "Weekly"),
                            ("MONTHLY", "Monthly"),
                            ("EVERY_SIX_MONTHS", "Every six months"),
                            ("YEARLY", "Yearly"),
                        ],
                        max_length=32,
                        null=True,
                    ),
                ),
                ("category", models.CharField(blank=True, max_length=120, null=True)),
                ("cancelled", models.BooleanField(default=False)),
                ("dueDate", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("lastPaidDate", models.DateTimeField(blank=True, null=True)),
                ("lastPaidDueDate", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Devices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ownerId",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("brand", models.CharField(blank=True, max_length=64, null=True)),
                ("deviceName", models.CharField(blank=True, max_length=120, null=True)),
                ("display", models.CharField(blank=True, max_length=120, null=True)),
                ("fcmToken", models.CharField(blank=True, max_length=255, null=True)),
                ("host", models.CharField(blank=True, max_length=120, null=True)),
                ("hostId", models.CharField(blank=True, max_length=120, null=True)),
                ("loginDate", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "creationDate",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "manufacturer",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                ("model", models.CharField(blank=True, max_length=120, null=True)),
                (
                    "androidVersion",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("isLoggedIn", models.BooleanField(default=False)),
                ("isBiometricAuthEnabled", models.BooleanField(default=False)),
                ("deviceId", models.CharField(blank=True, max_length=120, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FeedBack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ownerId",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "feedBackVersion",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("package", models.CharField(blank=True, max_length=64, null=True)),
                ("buildNumber", models.CharField(blank=True, max_length=64, null=True)),
                ("feedback", models.TextField(blank=True, null=True)),
                ("createdDate", models.DateField(blank=True, null=True)),
                ("tags", models.CharField(blank=True, max_length=255, null=True)),
                ("userId", models.CharField(blank=True, max_length=64, null=True)),
                ("user", models.CharField(blank=True, max_length=64, null=True)),
                ("rating", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Transactions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ownerId",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("ownerId_str", models.CharField(blank=True, max_length=64, null=True)),
                ("amount", models.FloatField(blank=True, null=True)),
                ("category", models.CharField(blank=True, max_length=120, null=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "merchantName",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "currencyCode",
                    models.CharField(blank=True, max_length=16, null=True),
                ),
                ("checkNumber", models.CharField(blank=True, max_length=64, null=True)),
                ("note", models.TextField(blank=True, null=True)),
                ("createdDate", models.DateTimeField(blank=True, null=True)),
                (
                    "transactionDate",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("path", models.CharField(blank=True, max_length=255, null=True)),
                ("isIncome", models.BooleanField(default=False)),
                (
                    "repeat",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DAILY", "Daily"),
                            ("WEEKLY", "Weekly"),
                            ("MONTHLY", "Monthly"),
                            ("EVERY_3_MONTHS", "Every 3 months"),
                            ("EVERY_6_MONTHS", "Every 6 months"),
                            ("YEARLY", "Yearly"),
                            ("NONE", "None"),
                        ],
                        max_length=32,
                        null=True,
                    ),
                ),
                ("isCashAccount", models.BooleanField(default=False)),
                ("canDelete", models.BooleanField(default=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="finance.account",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RecursiveTransactions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ownerId",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sourceId", models.CharField(blank=True, max_length=64, null=True)),
                ("tableName", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "repeat",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DAILY", "Daily"),
                            ("WEEKLY", "Weekly"),
                            ("MONTHLY", "Monthly"),
                            ("EVERY_3_MONTHS", "Every 3 months"),
                            ("EVERY_6_MONTHS", "Every 6 months"),
                            ("YEARLY", "Yearly"),
                            ("NONE", "None"),
                        ],
                        max_length=32,
                        null=True,
                    ),
                ),
                ("recursiveUpdatedDate", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Premium",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ownerId",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("messageFromGooglePlay", models.TextField(blank=True, null=True)),
                (
                    "planIdentifier",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "offeringIdentifier",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "productTitle",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("price", models.CharField(blank=True, max_length=32, null=True)),
                ("priceCost", models.CharField(blank=True, max_length=32, null=True)),
                (
                    "currencyCode",
                    models.CharField(blank=True, max_length=16, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("purchaseDate", models.DateTimeField(blank=True, null=True)),
                ("isActive", models.BooleanField(default=False)),
                (
                    "billingIssueDetectedAt",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "expirationDate",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("isSandbox", models.BooleanField(default=False)),
                (
                    "latestPurchaseDate",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "originalPurchaseDate",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "periodTypeName",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("periodTypeIndex", models.IntegerField(blank=True, null=True)),
                (
                    "productIdentifier",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "unsubscribeDetectedAt",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("willRenew", models.BooleanField(default=False)),
                ("plan", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "premiumStartDate",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "premiumEndDate",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("isPremium", models.BooleanField(default=False)),
                ("isExpired", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PaidMonths",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ownerId",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("paidMonth", models.DateTimeField(blank=True, null=True)),
                ("accountId", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "bills",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paidMonths",
                        to="finance.bills",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LoginInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ownerId",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("latitude", models.CharField(blank=True, max_length=64, null=True)),
                ("longitude", models.CharField(blank=True, max_length=64, null=True)),
                ("loginDate", models.DateTimeField(blank=True, null=True)),
                (
                    "devices",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="LoginInformations",
                        to="finance.devices",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ownerId",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("goalName", models.CharField(blank=True, max_length=120, null=True)),
                ("goalDesc", models.TextField(blank=True, null=True)),
                ("goalType", models.CharField(blank=True, max_length=64, null=True)),
                ("amount", models.FloatField(blank=True, null=True)),
                ("savedAmount", models.FloatField(blank=True, default=0, null=True)),
                ("duration", models.IntegerField(blank=True, null=True)),
                ("goalCategory", models.IntegerField(blank=True, null=True)),
                ("createdDate", models.DateTimeField(blank=True, null=True)),
                ("updatedDate", models.DateTimeField(blank=True, null=True)),
                (
                    "notification",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("isCompleted", models.BooleanField(default=False)),
                ("uniqueId", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ownerId",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("owner_id", models.CharField(blank=True, max_length=64, null=True)),
                ("type", models.IntegerField(blank=True, null=True)),
                (
                    "untitledfield",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("createdDate", models.DateTimeField(blank=True, null=True)),
                ("updatedDate", models.DateTimeField(blank=True, null=True)),
                ("amount", models.FloatField(blank=True, null=True)),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Balances",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ownerId",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("accountId", models.CharField(blank=True, max_length=64, null=True)),
                ("available", models.FloatField(blank=True, default=0, null=True)),
                ("current", models.FloatField(blank=True, default=0, null=True)),
                ("limit", models.FloatField(blank=True, default=0, null=True)),
                ("createdDate", models.DateTimeField(blank=True, null=True)),
                ("updatedDate", models.DateTimeField(blank=True, null=True)),
                (
                    "accountBalances",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="finance.accountbalances",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ownerId",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("value", models.FloatField(blank=True, default=0, null=True)),
                ("income", models.FloatField(blank=True, default=0, null=True)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("lattitude", models.FloatField(blank=True, null=True)),
                ("longnitude", models.FloatField(blank=True, null=True)),
                ("path", models.CharField(blank=True, max_length=255, null=True)),
                ("createdDate", models.DateTimeField(blank=True, null=True)),
                ("updatedDate", models.DateTimeField(blank=True, null=True)),
                ("addRevenueToAccount", models.BooleanField(default=False)),
                (
                    "repeat",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DAILY", "Daily"),
                            ("WEEKLY", "Weekly"),
                            ("MONTHLY", "Monthly"),
                            ("EVERY_3_MONTHS", "Every 3 months"),
                            ("EVERY_6_MONTHS", "Every 6 months"),
                            ("YEARLY", "Yearly"),
                            ("NONE", "None"),
                        ],
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Achieved",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ownerId",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("owner_id", models.CharField(blank=True, max_length=64, null=True)),
                ("amount", models.FloatField(blank=True, null=True)),
                ("achievedDate", models.DateTimeField(blank=True, null=True)),
                (
                    "goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievedGoals",
                        to="finance.goal",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
