# Generated by Django 4.2.23 on 2025-09-21 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0005_alter_category_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="institution_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="mask",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="plaid_access_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="plaid_item_id",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="public_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
